services:
  valkey:
    image: valkey/valkey:8
    container_name: valkey
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    environment:
      - VALKEY_USERNAME=default
      - VALKEY_PASSWORD=password
    command: valkey-server --requirepass password
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "valkey-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 3s
      retries: 5

volumes:
  valkey_data:
    driver: local
